//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package org.im4java.script;

import java.io.File;
import java.util.Calendar;

public class BashScriptGenerator extends AbstractScriptGenerator {
    public BashScriptGenerator() {
        this.ESC_EOL = '\\';
        this.ESC_SPECIAL = '\\';
    }

    protected void writeHeader() {
        this.getWriter().println("#!/bin/bash\n#-------------------------------------------------------\n# Bash-script autogenerated by im4java\n# at " + Calendar.getInstance().getTime() + "\n" + "#-------------------------------------------------------\n");
        String var1 = this.getSearchPath();
        if (var1 != null) {
            this.getWriter().println("export PATH=" + var1 + File.pathSeparator + "$PATH\n");
        }

    }

    protected String getScriptArg(String var1) {
        ++this.iArgIndex;
        return var1.length() > "?img?".length() ? "\"${" + this.iArgIndex + "}\"" + var1.substring("?img?".length()) : "\"${" + this.iArgIndex + "}\"";
    }

    protected String quote(String var1) {
        return var1.indexOf(34) == -1 ? '"' + var1 + '"' : '"' + var1.replace("\"", this.ESC_SPECIAL + "\"") + '"';
    }
}
