//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package org.im4java.script;

import java.io.File;
import java.util.Calendar;

public class CmdScriptGenerator extends AbstractScriptGenerator {
    public CmdScriptGenerator() {
        this.ESC_EOL = '^';
        this.ESC_SPECIAL = '^';
    }

    protected void writeHeader() {
        this.getWriter().println("@echo off\nREM -------------------------------------------------------\nREM  Cmd-script autogenerated by im4java\nREM  at " + Calendar.getInstance().getTime() + "\n" + "REM -------------------------------------------------------\n");
        String var1 = this.getSearchPath();
        if (var1 != null) {
            this.getWriter().println("set PATH=" + var1 + File.pathSeparator + "%PATH%\n");
        }

    }

    protected String getScriptArg(String var1) {
        ++this.iArgIndex;
        return var1.length() > "?img?".length() ? "\"%~" + this.iArgIndex + "\"" + var1.substring("?img?".length()) : "\"%~" + this.iArgIndex + "\"";
    }

    protected String quote(String var1) {
        return var1.indexOf(34) == -1 ? '"' + var1 + '"' : '"' + var1.replace("\"", "'") + '"';
    }
}
